version: '3.8'

services:
  redis:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    environment:
      REDIS_ARGS: "--appendonly yes"

  restllm:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "uvicorn", "restllm.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000", "--workers", "2", "--log-level", "info"]
    volumes:
      - ./src:/app/src
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8000:8000"
      - "11434:11434"
    depends_on:
      - redis
    environment:
      REDIS_DSN: redis://redis:6379/0
      OLLAMA_BASE_URL: http://localhost:11434
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOSTNAME: ${EMAIL_HOSTNAME}

  schematest:
    image: schemathesis/schemathesis:stable
    profiles:
      - excluded
    command: >
      run http://restllm:8000/openapi.json
    depends_on:
      - restllm